/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RouterManager } from "./RouterManager";
export * as factories from "./factories";
export { RouterManager__factory } from "./factories/RouterManager__factory";
